server:
  port: 1111
eureka:
  instance:
    hostname: peer1
    another: peer2
    port: 1112
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.another}:${eureka.instance.port}/eureka/
    register-with-eureka: true
    fetch-registry: true